services:
    burn-station-flask:
        build:
            context: ./flask
            dockerfile: Dockerfile
        container_name: burn_station_flask
        volumes:
            - ./flask:/app
        privileged: true
        ports:
            - "8011:8011"
        restart: unless-stopped
        environment:
            - PYTHONPATH=/app
            - TZ=America/Los_Angeles
        command: sh -c "PYTHONPATH=/app python -u app.py --host=0.0.0.0 --port=8011 & echo $! > /tmp/pid; tail -f /dev/null"
    
    burn-station-next:
        build:
            context: ./next
            dockerfile: Dockerfile
        container_name: burn_station_next
        volumes:
            - ./next:/workspace
        privileged: true
        ports:
            - "8010:8010"
        restart: unless-stopped
        environment:
            - TZ=America/Los_Angeles
        command: sh -c "npx next dev & echo $! > /tmp/pid; tail -f /dev/null"